# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
