# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='contact_details',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='customers',
            name='date_of_registration',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
